<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="10" failures="0" skipped="0" tests="10" time="0.781" timestamp="2023-04-09T20:55:21.756360" hostname="ta521.wpa.dal.ca"><testcase classname="" name="tests.config_test" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/ashutoshsagar/Documents/ASDC/Student_marketplace/group11/Accounts/tests/config_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../opt/anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/config_test.py:3: in &lt;module&gt;
    from accounts.config import Config, DevelopmentConfig, ProductionConfig
accounts/__init__.py:4: in &lt;module&gt;
    from flask_cors import CORS
E   ModuleNotFoundError: No module named 'flask_cors'</error></testcase><testcase classname="" name="tests.emailsend_test" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/ashutoshsagar/Documents/ASDC/Student_marketplace/group11/Accounts/tests/emailsend_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../opt/anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/emailsend_test.py:3: in &lt;module&gt;
    from accounts.emailsend import email_send
accounts/__init__.py:4: in &lt;module&gt;
    from flask_cors import CORS
E   ModuleNotFoundError: No module named 'flask_cors'</error></testcase><testcase classname="" name="tests.generateOTP_test" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/ashutoshsagar/Documents/ASDC/Student_marketplace/group11/Accounts/tests/generateOTP_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../opt/anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/generateOTP_test.py:1: in &lt;module&gt;
    from accounts.generateOTP import generate_otp
accounts/__init__.py:4: in &lt;module&gt;
    from flask_cors import CORS
E   ModuleNotFoundError: No module named 'flask_cors'</error></testcase><testcase classname="" name="tests.passwordGenerator_test" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/ashutoshsagar/Documents/ASDC/Student_marketplace/group11/Accounts/tests/passwordGenerator_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../opt/anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/passwordGenerator_test.py:2: in &lt;module&gt;
    from accounts.passwordGenerator import generate_password
accounts/__init__.py:4: in &lt;module&gt;
    from flask_cors import CORS
E   ModuleNotFoundError: No module named 'flask_cors'</error></testcase><testcase classname="" name="tests.dto.credentials_test" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/ashutoshsagar/Documents/ASDC/Student_marketplace/group11/Accounts/tests/dto/credentials_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../opt/anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/dto/credentials_test.py:2: in &lt;module&gt;
    from accounts.dto.credentials import Credentials, CredentialsSchema, ValidationError
accounts/__init__.py:4: in &lt;module&gt;
    from flask_cors import CORS
E   ModuleNotFoundError: No module named 'flask_cors'</error></testcase><testcase classname="" name="tests.dto.user_creation_test" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/ashutoshsagar/Documents/ASDC/Student_marketplace/group11/Accounts/tests/dto/user_creation_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../opt/anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/dto/user_creation_test.py:2: in &lt;module&gt;
    from accounts.dto.user_creation import UserCreationSchema, UserVerification, UserVerifyEmailSchema, UserReset, \
accounts/__init__.py:4: in &lt;module&gt;
    from flask_cors import CORS
E   ModuleNotFoundError: No module named 'flask_cors'</error></testcase><testcase classname="" name="tests.routes.auth_test" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/ashutoshsagar/Documents/ASDC/Student_marketplace/group11/Accounts/tests/routes/auth_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../opt/anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/routes/auth_test.py:2: in &lt;module&gt;
    from accounts import db
accounts/__init__.py:4: in &lt;module&gt;
    from flask_cors import CORS
E   ModuleNotFoundError: No module named 'flask_cors'</error></testcase><testcase classname="" name="tests.routes.error_test" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/ashutoshsagar/Documents/ASDC/Student_marketplace/group11/Accounts/tests/routes/error_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../opt/anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/routes/error_test.py:5: in &lt;module&gt;
    from marshmallow import ValidationError
E   ModuleNotFoundError: No module named 'marshmallow'</error></testcase><testcase classname="" name="tests.routes.health_test" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/ashutoshsagar/Documents/ASDC/Student_marketplace/group11/Accounts/tests/routes/health_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../opt/anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/routes/health_test.py:2: in &lt;module&gt;
    from accounts.routes.health import health_bp
accounts/__init__.py:4: in &lt;module&gt;
    from flask_cors import CORS
E   ModuleNotFoundError: No module named 'flask_cors'</error></testcase><testcase classname="" name="tests.routes.users_test" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/ashutoshsagar/Documents/ASDC/Student_marketplace/group11/Accounts/tests/routes/users_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../opt/anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/routes/users_test.py:5: in &lt;module&gt;
    from accounts.models.user import User
accounts/__init__.py:4: in &lt;module&gt;
    from flask_cors import CORS
E   ModuleNotFoundError: No module named 'flask_cors'</error></testcase></testsuite></testsuites>